files:
  include: "src/styles/**/*.scss"

# rules:
#   class-name-format: 0
#   force-attribute-nesting: 0
#   force-element-nesting: 0
#   force-pseudo-nesting: 0
#   id-name-format: 0
#   nesting-depth: 0
#   no-color-literals: 0
#   no-important: 0
#   no-invalid-hex: 0
#   no-qualifying-elements: 0
#   no-transition-all: 0
#   no-vendor-prefixes: 0
#   property-sort-order: 0
